### ISSUE TITLE
pydantic-core 2.14.6 unusable on Linux 64

### ISSUE THREAD

**Issue by samuelcolvin** [conda-forge/pydantic-core-feedstock#79] opened 2023-12-22 16:04 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

According to https://github.com/pydantic/pydantic/issues/8429 CI pipelines have started breaking in the last few hours after we released pydantic 2.5.3 with

```
ImportError: cannot import name 'PydanticUndefined' from 'pydantic_core' (unknown location)
```

Seems to be an issue with the pydantic-corer binaries for 2.14.6. related to https://github.com/conda-forge/pydantic-core-feedstock/pull/78

@conda-forge-admin anyone have any ideas.

### Installed packages

```shell
see https://github.com/pydantic/pydantic/issues/8429 and https://github.com/scikit-learn/scikit-learn/issues/28004
```

### Environment info

```shell
Azure CI on Linux 64.
```

**Comment by edgBR** [comment] 2023-12-22 19:10
Hi @conda-forge-admin can you please check?

**Comment by xhochy** [comment] 2023-12-22 19:50
> @conda-forge-admin anyone have any ideas.

Better ping @conda-forge/pydantic-core or @ conda-forge/help-python, @conda-forge-admin is a bot.

**Comment by xhochy** [comment] 2023-12-22 19:51
Testing this now in https://github.com/conda-forge/pydantic-core-feedstock/pull/80 Locally, I couldn't reproduce it on `osx-arm64`.

**Comment by davidhewitt** [comment] 2023-12-22 20:50
Well I can see what's wrong; the pydantic_core directory which gets installed is missing all the pure-python source:

This is 2.14.5:

```
# ls -l /opt/conda/lib/python3.11/site-packages/pydantic_core/
total 5048
-rw-r--r-- 2 root root    4197 Nov 22 14:46 __init__.py
drwxr-xr-x 2 root root    4096 Dec 22 20:47 __pycache__
-rwxr-xr-x 2 root root 4988336 Nov 22 14:46 _pydantic_core.cpython-311-x86_64-linux-gnu.so
-rw-r--r-- 2 root root   32246 Nov 22 14:46 _pydantic_core.pyi
-rw-r--r-- 2 root root  132810 Nov 22 14:46 core_schema.py
-rw-r--r-- 2 root root       0 Nov 22 14:46 py.typed
```

This is 2.14.6:

```
# ls -l /opt/conda/lib/python3.11/site-packages/pydantic_core/
total 4868
-rwxr-xr-x 2 root root 4984240 Dec 21 21:57 _pydantic_core.cpython-311-x86_64-linux-gnu.so
```

... as to _why_ this is the case, is not immediately obvious to me...

**Comment by hmaarrfk** [comment] 2023-12-22 22:31
Other linux packages are also broken.

**Comment by hmaarrfk** [comment] 2023-12-22 22:33
I'm trying to mark things as broken https://github.com/conda-forge/admin-requests/pull/900 so that others don't get disrupted during our debugging.

**Comment by edgBR** [comment] 2023-12-23 08:43
Hi @xhochy 


The problem persist:


https://dev.azure.com/scikit-learn/scikit-learn/_build/results?buildId=61825&view=logs&j=dde5042c-7464-5d47-9507-31bdd2ee0a3a&t=7d852497-2547-55fa-986f-0b436c028d7e

Please reopen

**Comment by xhochy** [comment] 2023-12-23 08:53
This is still using build 0. This has been marked as broken. Probably you will need to wait 30-60 min more until the CDN cache has cleared.

**Comment by glemaitre** [comment] 2023-12-23 11:27
Thanks to be super reactive. I confirm that the build is available now.

**Comment by hmaarrfk** [comment] 2023-12-23 11:30
We also marked the other builds as broken.

**Closed by hmaarrfk** 2023-12-23 11:30 UTC
Labels: bug

**Comment by edgBR** [comment] 2023-12-23 11:37
Thanks @hmaarrfk 

Lighting fast support!
